In [1]:
#info on the iris dataset
#https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.names
import pandas as pd
import numpy as np
%matplotlib inline
data = pd.read_csv("datasets/iris.csv",names=["sepal_l","sepal_w","petal_l","petal_w","class"])
data.head()

sepal_l  sepal_w  petal_l  petal_w        class
0      5.1      3.5      1.4      0.2  Iris-setosa
1      4.9      3.0      1.4      0.2  Iris-setosa
2      4.7      3.2      1.3      0.2  Iris-setosa
3      4.6      3.1      1.5      0.2  Iris-setosa
4      5.0      3.6      1.4      0.2  Iris-setosa

In [2]:
print(data["class"].unique())
#let's keep things simple and only have a binary regressor
data = data[data["class"].map(lambda x: x != "Iris-setosa")]
print(data["class"].unique())

['Iris-setosa' 'Iris-versicolor' 'Iris-virginica']
['Iris-versicolor' 'Iris-virginica']


In [45]:
#this was confusing me so much becaus eI haven't taken linear alg yet but matrix multiplication = dot product of matrix A and transpose(matrix B)
def sigmoid(z):
    return 1/(1+np.e**(-z))

def log_likelyhood(weights,x,y):
    scores = np.dot(x, weights)
    ll = np.sum( y*scores - np.log(1 + np.exp(scores)) )
    return ll

def logistic_regression(x,y, num_steps = 1000, learning_rate = 0.1):
    weights = np.zeros(x.shape[1])
    for cur in range(num_steps):
        scores = np.dot(x,weights)
        preds = sigmoid(scores)
        
        #update weights
        error = y - preds
        gradient = np.dot(x.T,error)
        weights += learning_rate*gradient
        
        if cur % (num_steps*0.1) == 0:
            print(log_likelyhood(weights, x,y))
    return weights

In [46]:
def turn_num(x):
    if x == "Iris-versicolor":
        return 1
    else:
        return 0
data["num_classes"] = data["class"].map(lambda x: turn_num(x))

In [48]:
#just like sklearn the error should be maximized, aka the magnitude of the error gets smaller
best_weights = logistic_regression(data[["sepal_l","sepal_w","petal_l","petal_w"]],data["num_classes"])

-1358.434000001872
-5151.0684251008
-157.1109590592541
-151.5621398578336
-143.17704317265236
-133.69008370637354
-122.13471394901264
-120.67661554920493
-119.13461415955554
-116.93209927399202


In [55]:
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression(C = 1e15)
clf.fit(data[["sepal_l","sepal_w","petal_l","petal_w"]],data["num_classes"])
print(best_weights)
print(clf.coef_)

[ 101.70281321   95.89560533 -141.60663026 -133.99254634]
[[  2.4636824    6.67654931  -9.41722491 -18.27097495]]


In [64]:
final_scores = np.dot(data[["sepal_l","sepal_w","petal_l","petal_w"]], best_weights)
preds = np.round(sigmoid(final_scores))

In [65]:
preds

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 0., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.,
       0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [70]:
print("my model: " + str((preds == data["num_classes"]).sum().astype(float) / len(preds)))
print("sklearn: " + str(clf.score(data[["sepal_l","sepal_w","petal_l","petal_w"]], data["num_classes"])))

my model: 0.96
sklearn: 0.98
